zuul:
  ignoredServices: '*'
  sensitiveHeaders: Authorization
  routes:
    shipwright:
      path: /shipwright/v1/**
      serviceId: sb-ref-composite-service

---
spring:
  profiles: local
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://sb-ref-config-service:8080
      fail-fast: true
